apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 5
  labels:
    run: hello-kagan
  name: hello-kagan
  namespace: default
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: hello-kagan
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: hello-kagan
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: '-XX:MaxRAM=450m'
        image: #IMAGE_NAME
        imagePullPolicy: Always
        name: hello-kagan
        ports:
        - containerPort: 11130
          protocol: TCP
        resources:
          limits:
            memory: 450Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
      
      
---

# SERVICE

apiVersion: v1
kind: Service
metadata:
  labels:
    run: hello-kagan
  name: hello-kagan
  namespace: default
spec:
  ports:
  - port: 11130
    protocol: TCP
    targetPort: 11130
  selector:
    run: hello-kagan
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
