apiVersion: v1
kind: Service
metadata:
  name: hello-app
spec:
  selector:
    role: hello-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 11130
      nodePort: 11130
  type: NodePort	
